---
title: "Loan_EDLD_Lab_11.Rmd"
author: "Christopher Loan"
date: "11/18/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F 
                      )
library(tidyverse)
library(rio)
library(here)
library(janitor)
```

# Tidy the *Project Reads* Data

## Loading data

```{r, data}
dat_original <- import(here("data", "Project_Reads_Scores.csv")) %>% clean_names()
```

## Removing columns (5-9, 24, & 25)

```{r, removing_cols}
dat_narrow <- dat_original %>% select(-c(5:9, 24, 25))
```

## Removing aggregates

```{r, removing_averages}
dat_narrow$student_id <- dat_narrow$student_id %>% 
  make_clean_names()
dat_filtered <- dat_narrow %>% 
  filter(student_id != "all_students_average" & 
         student_id != "all_students_average_2" &
         student_id != "all_students_average_3") 
```

## Tidying data

```{r, tidying}
dat_renamed <- dat_filtered %>% 
  rename(unit_56_score = unit_5_6_score,
         unit_56_percent = unit_5_6_percent) 

dat_pivoted_1 <- dat_renamed %>% 
  pivot_longer(cols = contains("unit"), 
               names_to = 
                 c("unit_number", ".value"),
               names_prefix = "unit_",
               names_sep = "_"
               )
dat <- dat_pivoted_1 %>% mutate(percent = parse_number(percent))
head(dat,3)
```

```{r, table}
dat %>% group_by(test_site) %>% 
  summarize(mean_pct = round(mean(percent),2)) %>% 
  knitr::kable(col.names = c('Test Site', 'Mean Percent Correct'))
```

```{r}
dat %>% 
  group_by(test_site) %>% 
  summarize(`Mean Percentage` = round(mean(percent),2)) %>%
  ggplot(aes(x = test_site, y = `Mean Percentage`)) + 
  geom_col(fill = c(2:4)) + 
  labs(x = 'Test Site', 
       title = 'Mean Percentage on Tests based on Testing Site') +
  theme_minimal() 
```

```{r}
dat %>% mutate(`test site` = test_site,
               `unit number` = unit_number) %>% 
  ggplot(aes(x = `unit number`,
             y = percent,
             size = score,
             color = `test site`
             )) +
  geom_jitter() +
  facet_wrap(~`test site`) + 
  theme_minimal() + 
  labs(title = 'Score Percentage* by Unit Number',
         subtitle = '*NOTE: raw score indicated by dot size')
```
